# Generated by Django 5.1.4 on 2024-12-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.category'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
