# Generated by Django 5.1.4 on 2024-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_inventory_stock_quantity_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='order_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
